AllCops:

  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'

  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'docs/**/*'

  DisplayCopNames: true

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/CyclomaticComplexity:
  Severity: warning

Style/PerlBackrefs:
  AutoCorrect: true

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: true

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 150

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 190

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Style/RedundantReturn:
  Enabled: false