# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "rainbow", "~>2.2"
gem "bundler-audit", "~>0.6"

gem "coveralls", "~>0.8", :group => [:development, :test]
gem "hoe-bundler", "~>1.3", :group => [:development, :test]
gem "hoe-doofus", "~>1.0", :group => [:development, :test]
gem "hoe-git", "~>1.6", :group => [:development, :test]
gem "hoe-reek", "~>1.1", :group => [:development, :test]
gem "hoe-rubocop", "~>1.0", :group => [:development, :test]
gem "hoe-rubygems", "~>1.0", :group => [:development, :test]
gem "hoe-travis", "~>1.3", :group => [:development, :test]
gem "hoe-version", "~>1.2", :group => [:development, :test]
gem "rake", "~>12.1", :group => [:development, :test]
gem "rdoc", "~>5.1", :group => [:development, :test]
gem "rubocop", "~>0.50", :group => [:development, :test]
gem "rspec", "~>3.7", :group => [:development, :test]
gem "hoe", "~>3.16", :group => [:development, :test]

# vim: syntax=ruby
