# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "rainbow", "~>3.0"
gem "bundler-audit", "~>0.6"

gem "hoe-bundler", "~>1.3", :group => [:development, :test]
gem "hoe-rubygems", "~>1.0", :group => [:development, :test]
gem "hoe-version", "~>1.2", :group => [:development, :test]
gem "rdoc", "~>5.1", :group => [:development, :test]
gem "rspec", "~>3.7", :group => [:development, :test]
gem "coveralls", "~>0.8", :group => [:development, :test]
gem "hoe", "~>3.17", :group => [:development, :test]

# vim: syntax=ruby
