# api_endpoint: http://private-77f5-gemnasium.apiary-mock.com
api_key: c916184c3e0892558476535b216f7442    # You personal (secret) API key. Get it at https://gemnasium.com/settings/api_access
project_name: hoe-manns    # A name to remember your project.
project_slug: 2a56a3d68e779b8be5caf118ab2700d8               # Unique slug for this project. Get it on the "project settings" page.
project_branch: master        # /!\ If you don't use git, remove this line
